#TZ1090 Platform support
snd-soc-tz1090-objs := tz1090-pcm.o
snd-soc-tz1090-i2s-objs := tz1090-i2s.o
obj-$(CONFIG_SND_TZ1090_SOC) += snd-soc-tz1090.o
obj-$(CONFIG_SND_TZ1090_SOC_I2S) += snd-soc-tz1090-i2s.o

#TZ1090 Machine support
snd-soc-01xx-objs := 01xx.o

obj-$(CONFIG_SND_TZ1090_SOC_TZ1090_01XX) += snd-soc-01xx.o


