#Chorus2 Platform support
snd-soc-chorus2-objs := chorus2-pcm.o
snd-soc-chorus2-i2s-objs := chorus2-i2s.o

obj-$(CONFIG_SND_CHORUS2_SOC) += snd-soc-chorus2.o
obj-$(CONFIG_SND_CHORUS2_SOC_I2S) += snd-soc-chorus2-i2s.o

#Chorus2 Machine support
snd-soc-atp-dp-objs := atp-dp.o

obj-$(CONFIG_SND_CHORUS2_SOC_ATP_DP) += snd-soc-atp-dp.o


