#
# Makefile for the Linux Meta-specific sysfs interfaces.
#

obj-$(CONFIG_METAG_CORE_SYSFS)		+= core-sysfs.o counters/
obj-$(CONFIG_METAG_WRITE_COMBINER)	+= write-combiner.o
obj-$(CONFIG_METAG_MEM_ARBITER)		+= memory-arbiter.o
obj-$(CONFIG_METAG_L2C_CONTROL)		+= l2cache-control.o
