#
# Makefile for the Meta performance counter specific device drivers.
#

obj-$(CONFIG_METAG_CYCLE_COUNTER)	+= cyclecount.o
obj-$(CONFIG_METAG_PERFORMANCE_COUNTER)	+= perfcount.o
obj-$(CONFIG_METAG_AMA_COUNTER)		+= amacount.o
