#
# Makefile for the comet 01SP/01TT board specific parts of the kernel
#

obj-y	:= setup.o

# HDMI Device
obj-$(CONFIG_TZ1090_01XX_HDMI_VID_OUT)	+= hdmi-out/
obj-$(CONFIG_TZ1090_01XX_DISPLAY)	+= display/
